### ISSUE TITLE
Need translation workflow?

### ISSUE THREAD

**Issue by sotayamashita** [nuxt/docs#125] opened 2017-05-29 03:40 UTC
In open source community, translation is important but it is very difficult so **we are creating localization tool to help translated ones updated as well.** :100: It's name is [GitLocalize](https://gitlocalize.com/). The reason that we built it was translation problem of Node.js.

It have been used in  **"[GitHub - vuejs/vue-ssr-docs](https://github.com/vuejs/vue-ssr-docs), [GitLocalize - vuejs/vue-ssr-docs](https://gitlocalize.com/repo/62)"** So I think it is a time to try our service in Nuxt.js community. We provide these features below:

- Have a split view to make people translate
- When original one is updated, we will notify translators
- Translation flow looks like a GitHub flow:
  1. Sync GitHub and GitLocalize
  2. Translate
  3. Create a review request such as Pull Request of GitHub
  4. GitLocalize will create pull request to GitHub repository
  5. And merge. That's it :sparkles: 

Looking forward to hearing your thoughts :smile:

cc:/ @gbezyuk, @inouetakuya, @DiyLecko, @mamboer, @chuyik

**Comment by sotayamashita** [comment] 2017-05-29 08:18
@alexchopin Wow. I appreciate you creating the repository on GitLocalize!

**Comment by sotayamashita** [comment] 2017-05-29 08:33
@alexchopin We found issues for parsing and I am figuring it out now. It will be solved soon :bow:

**Comment by alexchopin** [comment] 2017-05-29 08:37
@sotayamashita Ok, Thanks.

**Comment by gbezyuk** [comment] 2017-05-29 14:11
ping @Alex-Sokolov

**Comment by sotayamashita** [comment] 2017-05-29 23:23
@gbezyuk 

I look into Translation Gang and it is rad.  I have a question about it.
Does Translation Gang help only people who want to translate something into Russian?

**Comment by inouetakuya** [comment] 2017-05-30 01:00
Cool !!!

**Comment by gbezyuk** [comment] 2017-05-30 06:02
@sotayamashita nope, it's supposed to be totally international.

**Comment by Atinux** [comment] 2017-05-30 09:16
Thank you @sotayamashita 

GitLocalize is a great project :+1:

**Comment by Atinux** [comment] 2017-05-30 09:31
Hi @sotayamashita 

Is there a way for our team to update the English files directly from GitLocalize?

**Comment by sotayamashita** [comment] 2017-05-30 15:33
@Atinux You can not edit English files directly from GitLocalize because it is localization tool. Do you  
 want to edit directly? and why?

**Comment by Atinux** [comment] 2017-05-31 10:11
Because I like the editor of GitLocalize @sotayamashita :)

**Comment by sotayamashita** [comment] 2017-06-01 05:10
@Atinux 

> Because I like the editor of GitLocalize @sotayamashita :)

Can I ask a few question?

- Why do you like GitLocalize editor? 
- What editor do you use to write markdown file or docs? 

Thanks in advance.

**Comment by chuyik** [comment] 2017-06-01 09:02
@sotayamashita 

GitLocalize is a great platform to organize and keep updating the translation.
But after looking into GitLocalize, I found that there are some serious problems.
I don't know if @sotayamashita you are the creator/developer of GitLocalize, and I wanna point out some here:

## Usability issues

1. Have to **edit the raw html** rather than markdown. As a translator, we should only edit the markdown and leaves the transformation job to the converter.
![image](https://cloud.githubusercontent.com/assets/6262943/26670378/0388a1dc-46e4-11e7-9623-d5e539c7cc2e.png)

2. **Incorrect highlight.** Maybe there're some bugs when converting the existing content on Github.
![image](https://cloud.githubusercontent.com/assets/6262943/26670538/9689e720-46e4-11e7-862e-f29ce1a42bdb.png)
Reproduce url: https://gitlocalize.com/repo/100/zh/en/guide/assets.md

3. **Misplaced content.** Some translation segment are linked wrong, just screwed.
![image](https://cloud.githubusercontent.com/assets/6262943/26671794/61a8a94c-46e9-11e7-8a07-d846cbb20eb0.png)
Reproduce url: https://gitlocalize.com/repo/100/zh/en/api/configuration-build.md

4. **Failed to link the segments.**
![image](https://cloud.githubusercontent.com/assets/6262943/26672016/275f779c-46ea-11e7-8f18-1d22d19923ef.png)
Reproduce url: https://gitlocalize.com/repo/100/zh/en/api/configuration-dev.md

---

Besides the issues mentioned above, I also suggest some features that may help improve the experience:

## Wishlist

1. Auto-resize editor box (<textarea />)
It's very crucial to a long paragraph.

2. Allow to revert changes
This is a good-to-have feature, especially for someone who want the previous translation back.

3. Batch PR
We should be allowed to send a PR that contains multiple markdown files, and review them once.

After all, I love GitLocalize, but yet to be mature.

**Comment by sotayamashita** [comment] 2017-06-01 12:22
@chuyik 

> I don't know if @sotayamashita you are the creator/developer of GitLocalize

I am an engineer of it.  :computer:
I appreciate you giving us feedback. We are trying to fix it. :muscle:

> 1. Auto-resize editor box (<textarea />)

I will fix soon

> 2. Allow to revert changes

I understand. I have a question. You want to see all history of each sentence?

> 3. Batch PR

It's little difficult now but I know the why you want it.

**Comment by chikathreesix** [comment] 2017-06-02 07:21
Hi @chuyik 

I am Ryo, also a creator of GitLocalize.
Thank you so much for your feedback!

> ## Usability issues
> 1. Have to edit the raw html rather than markdown. As a translator, we should only edit the markdown and leaves the transformation job to the converter.

I am fixing it by showing the html tags as more abstracted format so that no need to take care of the details of the tag.

> 2. Incorrect highlight. Maybe there're some bugs when converting the existing content on Github.

Looking into it now and will be fixed soon

> 3. Misplaced content. Some translation segment are linked wrong, just screwed.

I fixed the linking on the file. Integrating with a project which already has translated resources is a bit tricky since the system needs to make sure that the translated and the original have exactly the same structure. I will look over all files to make sure nothing screwed and I might need to send some pull requests to fix the conflicts.

> 4. Failed to link the segments.

This is also related to 3. It failed because the translated file and the original file have a different structure. Let me send a pull request for the Chinese file to get along with the English one.

Thanks again for giving us great feedbacks!

**Comment by chuyik** [comment] 2017-06-02 08:41
@sotayamashita @christiannwamba 
I didn't expect such quick responses from you guys 👍 , you are welcome.

> You want to see all history of each sentence?

Hey Sota, again this is good to have, but of course I will want it.
I think it's common to revise the texts back and forth during the translation. 
But I don't mean a full history of it, maybe just a UNDO can help. Imagine when I remove a sentence with some mistake, and the texts are gone along with the submit button hit.

I love to interview new stuff, but I don't know if it's cool to keep the conversation here since it's irrelevant to nuxt/docs. So if any issues found I may use email or any other tools better for feedback.

**Closed** 2017-08-23 09:33 UTC
Labels: enhancement
