### ISSUE TITLE
document nuxt-start

### ISSUE THREAD

**Issue by far-blue** [nuxt/docs#1430] opened 2019-06-05 22:39 UTC
### What problem does this feature solve?

At the moment, the nuxt npm package has dependencies such as @nuxt/webpack that pull in webpack, babel, postcss, node-sass etc. While this is fine in a dev or build environment it significantly increases the deploy size and security surface of a production SSR application.

### What does the proposed changes look like?

Rather than the current nuxt package, 2 packages would be available - one with the build / dev dependencies and one without. Kind of line `micro` and `micro-dev`. I suggest the full-fat version continue to be `nuxt` while the new one could be `@nuxt/server-runtime` or something.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9315">#c9315</a>)</em></sub></div>

**Comment by pi0** [comment] 2019-06-06 19:22
(transferred to docs)

**Comment by far-blue** [comment] 2019-06-06 22:48
As long as I understand how it works I'm happy to contribute a PR. Let me have a play and maybe ask questions before I write something inaccurate though ;)

**Comment by ngaiwe** [comment] 2019-06-12 03:34
feserver 80端口代理localhost:3000 启动项目用localhost不能热更新

**Comment by blowsie** [comment] 2019-06-18 12:46
Duplicates https://github.com/nuxt/docs/issues/1428

**Comment by manniL** [comment] 2019-06-27 08:45
Duplicate of #1428

**Closed by manniL** 2019-06-27 08:45 UTC
