### ISSUE TITLE
TypeScript setup broken in newest version

### ISSUE THREAD

**Issue by khrome83** [nuxt/docs#1323] opened 2019-04-17 11:53 UTC
### Version

[2.5.x](https://github.com/docs/releases/tag/2.5.x)

### Reproduction link

[https://nuxtjs.org/guide/typescript/](https://nuxtjs.org/guide/typescript/)

### Steps to reproduce

Follow Installation Guide Here - https://nuxtjs.org/guide/typescript/

### What is expected ?

TypeScript works as expected...

### What is actually happening?

The pages/feed.vue file throws a TypeScript error. 
![Screen Shot 2019-04-17 at 6.51.05 AM.png](https://cmty.s3.eu-west-1.amazonaws.com/74384145/1b9118b0-6107-11e9-bd09-e59dc5c6046e.png)

### Additional comments?

The code is copied and pasted exactly. After tons of research, I can't find a workaround with the exception of setting up `*.d.ts` files and overriding the behavior or turning off `StrictFunctions`. I am new to typescript​ and was really relying on this guide to integrate with it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c192">#c192</a>)</em></sub></div>

**Comment by khrome83** [comment] 2019-04-18 11:20
The community TypeScript template also uses `nuxt-property-decorator`. I don't know if that is preferred over `vue-property-decorator`.

**Comment by khrome83** [comment] 2019-04-18 11:34
Using `nuxt-property-decorator` page as the example, I created this, which does not throw any errors - 

```
<template>
  <section>
    <h1 class="header">Nuxt TypeScript Starter</h1>
    <div class="cards">
      <Card v-for="person in people" :key="person.id" :person="person"></Card>
    </div>
  </section>
</template>

<script lang="ts">
import { Component, Vue } from "nuxt-property-decorator";
import { State } from "vuex-class";
import { Person } from "~/types";
import Card from "~/components/Card.vue";

@Component({
  components: {
    Card
  }
})
export default class extends Vue {
  @State people!: Person;
}
</script>

<style scoped>
.header {
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}

.cards {
  display: flex;
  flex-wrap: wrap;
}
</style>
```
I am still knew to typescript,  and just getting back into Nuxt/Vue, so let me know if this is the right direction. If it is, I can make a PR for the doc and update it for you.

**Comment by kevinmarrec** [comment] 2019-04-18 12:02
@khrome83

Regarding `nuxt-property-decorator`, it's just a wrapper of `vue-property-decorator` and 
https://github.com/nuxt-community/nuxt-property-decorator/blob/master/src/nuxt-property-decorator.ts#L7

I don't personally really like it cause some of the hooks should be IMO kept under `@Component` section and not in the class, to have more comprehensive code.

Furthermore these hooks in class only work if they are functions, so for example `transition` which could be a string, cause issues using the `nuxt-property-decorator`.

I think you other issues are because you were trying to use `components` property inside the Vue class instead of the `@Component` decorator options.

---

For the missing `interface` keyword, nice find ! Feel free to open a PR to fix it :)

**Comment by khrome83** [comment] 2019-04-18 12:27
@kevinmarrec - the original post, the screenshot above, is using `components` inside of @Component. It is 100% the code that is on the Nuxt w/ Typescript Tutorial.

That still seems like a valid bug. The post I had with `nuxt-property-decorator` is just a possible solution. 

But it's clear that I can't use the component object within the @Component. Even after I move the Import out, and just referenced it above, `asyncData` has the same issue. Hence moving it into the class itself.

I can open a PR for the interface. In the meantime @kevinmarrec can you explain the original error?

**Comment by kevinmarrec** [comment] 2019-04-18 18:57
@khrome83 I'm not able to reproduce your issue :
![Screenshot from 2019-04-18 20-53-27](https://user-images.githubusercontent.com/25272043/56384171-0ee4e900-621c-11e9-8f4e-20ff7a80cec0.png)

So I think it's something wrong within your project configuration.
Could you link a repository with reproduction ?

You can also try to update to Nuxt `2.6` (issue description is mentionning `2.5.x`)

**Comment by khrome83** [comment] 2019-04-19 01:03
I originally saw it with Nuxt 2.5.x. I then used https://github.com/nuxt-community/typescript-template to build a new folder. This was 2.6.1. I copied the code from the docs into that and saw the same output.  

Do you have `Vetur` and `VSCode` updated? I am using - 

Vetur - 0.18.1
VS Code - 1.33.1

I am wondering if it has to do with the IDE and newer version?

**Comment by kevinmarrec** [comment] 2019-04-19 07:40
I don't have any issues starting a new project with docs instructions, did you try following the docs from the beginning without requiring to external template since 2.6.x ?

**Comment by kevinmarrec** [comment] 2019-06-15 16:37
@khrome83 Is this resolved ? Can we close the issue ?

**Closed** 2019-06-15 20:33 UTC
Labels: cmty:bug-report

**Comment by khrome83** [comment] 2019-06-16 16:12
I ended up using nuxt property decorator. I would say close the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
